Update ci-sonar.yml

diff --git a/.github/workflows/ci-sonar.yml b/.github/workflows/ci-sonar.yml
--- a/.github/workflows/ci-sonar.yml
+++ b/.github/workflows/ci-sonar.yml
@@ -41,28 +41,6 @@ jobs:
 
     - name: Run BookLendingService.Application.Tests with Coverlet
       run: dotnet test BookLendingService.Application.Tests/BookLendingService.Application.Tests.csproj --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=coverage-report/BookLendingService.Application.Tests.cobertura.xml
-    
-    - name: Debug:List coverage XML files
-      run: |
-        echo "Checking for coverage files:"
-        find coverage-report -name "*.cobertura.xml" -exec ls -la {} \;
-
-    - name: Debug:Check merged coverage file
-      run: ls -l coverage-report/merged
-
-    - name: Debug:Print coverage XML (if present)
-      run: |
-        COVERAGE_XML="coverage-report/coverage.cobertura.xml"
-        if [ -f "$COVERAGE_XML" ]; then
-          echo "Coverage XML found:"
-          cat "$COVERAGE_XML"
-        else
-          echo "Coverage XML not found at $COVERAGE_XML"
-          # Show any file that was produced for easier debugging
-          echo "Other files in coverage-report:"
-          ls -la coverage-report || true
-          exit 1
-        fi
 
     - name: Install ReportGenerator
       run: dotnet tool install --global dotnet-reportgenerator-globaltool
@@ -74,7 +52,29 @@ jobs:
           echo "No coverage reports found to merge."
           exit 1
         }
+    
+    - name: Debug:List coverage XML files
+      run: |
+        echo "Checking for coverage files:"
+        find coverage-report -name "*.cobertura.xml" -exec ls -la {} \;
 
+    - name: Debug:Check merged coverage file
+      run: ls -l coverage-report/merged
+
+    - name: Debug:Print coverage XML (if present)
+      run: |
+        COVERAGE_XML="coverage-report/merged/coverage.cobertura.xml"
+        if [ -f "$COVERAGE_XML" ]; then
+          echo "Merged Coverage XML found:"
+          cat "$COVERAGE_XML"
+        else
+          echo "Merged Coverage XML not found at $COVERAGE_XML"
+          # Show any file that was produced for easier debugging
+          echo "Other files in coverage-report/merged:"
+          ls -la coverage-report/merged  || true
+          exit 1
+        fi
+  
     - name: End SonarCloud analysis
       env:
         SECRET: ${{ secrets.SONAR_TOKEN }}
